name: Main workflow

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ocaml-version:
          - 4.10.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: opam pin add dvm.dev . --no-action

      - run: opam depext dvm --yes --with-doc --with-test

      - run: opam install . --deps-only --with-doc --with-test

      - run: opam exec -- make build

      - name: Copy and rename binary
        run: cp _build/default/bin/main.exe ./dvm

      - name: Upload binary to artifact
        uses: actions/upload-artifact@v2
        with:
          name: dvm-${{ matrix.os }}
          path: dvm

      - name: Prepare release asset
        if: contains(github.ref, 'refs/tags')
        run: tar -zcvf dvm-x86_64-${{ matrix.os }}.tar.gz dvm

      - name: Create release
        if: contains(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v1
        with:
          files: dvm-x86_64-${{ matrix.os }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
